spring:
  application:
    key: ${LMP_SERVICE_KEY:08a23cc95cb94ec29728e1b1fae5f1ab}
    token: ${LMP_SERVICE_TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlTmFtZSI6IjExMTIiLCJzZXJ2aWNlS2V5IjoiMDhhMjNjYzk1Y2I5NGVjMjk3MjhlMWIxZmFlNWYxYWIiLCJzZXJ2aWNlVHlwZSI6IjEiLCJzZXJ2aWNlQXBwIjoiNTA0Iiwic2VydmljZUNsdXN0ZXIiOiIyIiwianRpIjoiNDI3MzEzMmEwNmJkNGRiNmFlYjc1Y2Y2ODYzODU2OTQiLCJpYXQiOjE1NzE2NjUxOTJ9._HNpPenCTwMhe0CgxkXrcaTt_u1BiuHRFnfkJIQuCrU}
  # 数据源配置
  main:
    allow-bean-definition-overriding: true
    enabled: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.postgresql.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:postgresql://dlms-postgre.postgres.database.azure.com:5432/dlms_common?useSSL=true&requireSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: dlmsadmin@dlms-postgre
        password: Dlms!1*8$4
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 100
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
#mybatis配置
mybatis-plus:
  type-aliases-package: com.lenovo.bigdata.delivery.dlms.common.CalendarShift.system
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false


##系统基础配置
config:
  #配置免认证url,逗号分隔
  anonUrl: /actuator/**,/swagger-ui.html,/webjars/**,/swagger-resources/**,/v2/api-docs/**,/csrf,/workflow/**,/attachment/**,/cochat/**
#
#swagger相关配置
swagger:
  #开启、关闭(true开启、false关闭),线上关闭
  enable: true
  #controller扫描根路径
  basePackage: com.lenovo.bigdata.delivery.dlms.attendance.server.controller
  title: DLMS业务接口详情
  description: Swagger2构建RESTful APIs
  contact:
    name: 联想DLMS项目组
    url: http://www.lenovo.com
    email: xxxx@lenovo.com
  version: 1.0
#
#feign 服务名定义
service:
  file: DLMS--dlms-file
  idUtil: DLMS--dlms-idutil
  hr: DLMS--dlms-hr
  system: DLMS--dlms-server-system
  flowable: DLMS--dlms-flowable
  email: DLMS--dlms-message



lmp:
  service:
    key: ${LMP_SERVICE_KEY:08a23cc95cb94ec29728e1b1fae5f1ab}
    token: ${LMP_SERVICE_TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlTmFtZSI6IjExMTIiLCJzZXJ2aWNlS2V5IjoiMDhhMjNjYzk1Y2I5NGVjMjk3MjhlMWIxZmFlNWYxYWIiLCJzZXJ2aWNlVHlwZSI6IjEiLCJzZXJ2aWNlQXBwIjoiNTA0Iiwic2VydmljZUNsdXN0ZXIiOiIyIiwianRpIjoiNDI3MzEzMmEwNmJkNGRiNmFlYjc1Y2Y2ODYzODU2OTQiLCJpYXQiOjE1NzE2NjUxOTJ9._HNpPenCTwMhe0CgxkXrcaTt_u1BiuHRFnfkJIQuCrU}
