server:
  port: 8080
  
spring:
  cloud:
    config:
      uri: https://lin-server.svc.azuremicroservices.io/config
eureka:
  client:
    service-url: https://lin-server.svc.azuremicroservices.io/eureka/eureka
