server:
  port: 8080
  
spring:
  application:
    name: democloud
  cloud:
    config:
      uri: https://lin-server.svc.azuremicroservices.io/config

eureka:
  client:
    serviceUrl:
      defaultZone: https://lin-server.svc.azuremicroservices.io/eureka/eureka
